### ISSUE TITLE
Training saved model cannot be loaded by eval

### ISSUE THREAD

**Issue by LouieBHLu** [zoeyuchao/maans#4]
I am encountering an issue that the model `global_actor_best.pt` cannot be loaded during evaluation. I've changed the name to `actor.pt` for correct loading. However, the keys simply do not match. The error message is shown as follows:
RuntimeError: Error(s) in loading state_dict for R_Actor:
        Missing key(s) in state_dict: "base.descon.0.weight", "base.descon.0.bias", "base.descon.3.to_qkv.weight", "base.descon.3.to_out.0.weight", "base.descon.3.to_out.0.bias", "base.descon.5.weight", "base.descon.5.bias". 
        Unexpected key(s) in state_dict: "base.descon.0.actor_pos_embedding", "base.descon.0.other_pos_embedding", "base.descon.0.encode_actor_net.weight", "base.descon.0.encode_actor_net.bias", "base.descon.0.encode_other_net.weight", "base.descon.0.encode_other_net.bias", "base.descon.0.spatial_attn_layers.0.0.norm.weight", "base.descon.0.spatial_attn_layers.0.0.norm.bias", "base.descon.0.spatial_attn_layers.0.0.fn.to_qkv.weight", "base.descon.0.spatial_attn_layers.0.0.fn.to_out.0.weight", "base.descon.0.spatial_attn_layers.0.0.fn.to_out.0.bias", "base.descon.0.spatial_attn_layers.0.1.norm.weight", "base.descon.0.spatial_attn_layers.0.1.norm.bias", "base.descon.0.spatial_attn_layers.0.1.fn.net.0.weight", "base.descon.0.spatial_attn_layers.0.1.fn.net.0.bias", "base.descon.0.spatial_attn_layers.0.1.fn.net.3.weight", "base.descon.0.spatial_attn_layers.0.1.fn.net.3.bias", "base.descon.0.spatial_attn_layers.1.0.norm.weight", "base.descon.0.spatial_attn_layers.1.0.norm.bias", "base.descon.0.spatial_attn_layers.1.0.fn.to_qkv.weight", "base.descon.0.spatial_attn_layers.1.0.fn.to_out.0.weight", "base.descon.0.spatial_attn_layers.1.0.fn.to_out.0.bias", "base.descon.0.spatial_attn_layers.1.1.norm.weight", "base.descon.0.spatial_attn_layers.1.1.norm.bias", "base.descon.0.spatial_attn_layers.1.1.fn.net.0.weight", "base.descon.0.spatial_attn_layers.1.1.fn.net.0.bias", "base.descon.0.spatial_attn_layers.1.1.fn.net.3.weight", "base.descon.0.spatial_attn_layers.1.1.fn.net.3.bias", "base.descon.0.agent_attn_layers.0.0.norm.weight", "base.descon.0.agent_attn_layers.0.0.norm.bias", "base.descon.0.agent_attn_layers.0.0.fn.to_qkv.weight", "base.descon.0.agent_attn_layers.0.0.fn.to_out.0.weight", "base.descon.0.agent_attn_layers.0.0.fn.to_out.0.bias", "base.descon.0.agent_attn_layers.0.1.norm.weight", "base.descon.0.agent_attn_layers.0.1.norm.bias", "base.descon.0.agent_attn_layers.0.1.fn.net.0.weight", "base.descon.0.agent_attn_layers.0.1.fn.net.0.bias", "base.descon.0.agent_attn_layers.0.1.fn.net.3.weight", "base.descon.0.agent_attn_layers.0.1.fn.net.3.bias", "base.descon.0.agent_attn_layers.1.0.norm.weight", "base.descon.0.agent_attn_layers.1.0.norm.bias", "base.descon.0.agent_attn_layers.1.0.fn.to_qkv.weight", "base.descon.0.agent_attn_layers.1.0.fn.to_out.0.weight", "base.descon.0.agent_attn_layers.1.0.fn.to_out.0.bias", "base.descon.0.agent_attn_layers.1.1.norm.weight", "base.descon.0.agent_attn_layers.1.1.norm.bias", "base.descon.0.agent_attn_layers.1.1.fn.net.0.weight", "base.descon.0.agent_attn_layers.1.1.fn.net.0.bias", "base.descon.0.agent_attn_layers.1.1.fn.net.3.weight", "base.descon.0.agent_attn_layers.1.1.fn.net.3.bias", "base.descon.0.cross_attn_layers.0.0.norm.weight", "base.descon.0.cross_attn_layers.0.0.norm.bias", "base.descon.0.cross_attn_layers.0.0.fn.to_qkv.weight", "base.descon.0.cross_attn_layers.0.0.fn.to_out.0.weight", "base.descon.0.cross_attn_layers.0.0.fn.to_out.0.bias", "base.descon.0.cross_attn_layers.0.1.norm.weight", "base.descon.0.cross_attn_layers.0.1.norm.bias", "base.descon.0.cross_attn_layers.0.1.fn.net.0.weight", "base.descon.0.cross_attn_layers.0.1.fn.net.0.bias", "base.descon.0.cross_attn_layers.0.1.fn.net.3.weight", "base.descon.0.cross_attn_layers.0.1.fn.net.3.bias", "base.descon.0.cross_attn_layers.0.2.weight", "base.descon.0.cross_attn_layers.0.2.bias", "base.descon.0.cross_attn_layers.0.3.weight", "base.descon.0.cross_attn_layers.0.4.to_q.weight", "base.descon.0.cross_attn_layers.0.4.to_out.0.weight", "base.descon.0.cross_attn_layers.0.4.to_out.0.bias", "base.descon.0.cross_attn_layers.0.5.norm.weight", "base.descon.0.cross_attn_layers.0.5.norm.bias", "base.descon.0.cross_attn_layers.0.5.fn.net.0.weight", "base.descon.0.cross_attn_layers.0.5.fn.net.0.bias", "base.descon.0.cross_attn_layers.0.5.fn.net.3.weight", "base.descon.0.cross_attn_layers.0.5.fn.net.3.bias", "base.descon.0.cross_attn_layers.1.0.norm.weight", "base.descon.0.cross_attn_layers.1.0.norm.bias", "base.descon.0.cross_attn_layers.1.0.fn.to_qkv.weight", "base.descon.0.cross_attn_layers.1.0.fn.to_out.0.weight", "base.descon.0.cross_attn_layers.1.0.fn.to_out.0.bias", "base.descon.0.cross_attn_layers.1.1.norm.weight", "base.descon.0.cross_attn_layers.1.1.norm.bias", "base.descon.0.cross_attn_layers.1.1.fn.net.0.weight", "base.descon.0.cross_attn_layers.1.1.fn.net.0.bias", "base.descon.0.cross_attn_layers.1.1.fn.net.3.weight", "base.descon.0.cross_attn_layers.1.1.fn.net.3.bias", "base.descon.0.cross_attn_layers.1.2.weight", "base.descon.0.cross_attn_layers.1.2.bias", "base.descon.0.cross_attn_layers.1.3.weight", "base.descon.0.cross_attn_layers.1.4.to_q.weight", "base.descon.0.cross_attn_layers.1.4.to_out.0.weight", "base.descon.0.cross_attn_layers.1.4.to_out.0.bias", "base.descon.0.cross_attn_layers.1.5.norm.weight", "base.descon.0.cross_attn_layers.1.5.norm.bias", "base.descon.0.cross_attn_layers.1.5.fn.net.0.weight", "base.descon.0.cross_attn_layers.1.5.fn.net.0.bias", "base.descon.0.cross_attn_layers.1.5.fn.net.3.weight", "base.descon.0.cross_attn_layers.1.5.fn.net.3.bias", "base.descon.0.out_norm.weight", "base.descon.0.out_norm.bias", "base.descon.1.weight", "base.descon.1.bias". 
        size mismatch for base.cnn.1.weight: copying a param with shape torch.Size([32, 6, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 14, 3, 3]).

Could you possibly provide a more detailed process for training and eval? like which models to use and etc.?

Thank you

**Comment by zoeyuchao** [comment]
sorry for the evaluation error. The provided evaluation script is wrong and we will update the code recently. please pay attention to the update.

**Comment by LouieBHLu** [comment]
Hey, really appreciate it! 

BTW, can you also include a little bit about how to switch rooms in a dataset? Now, it's only rendering one room I guess (in evaluation)? Where can I or which parameter I can use to run rendering for all rooms in Gibson dataset for example or a selected room? 

Thank you!

**Comment by zoeyuchao** [comment]
You can change the parameter named 'scene_id' in evaluation script to the scene you want to render

**Comment by CHY981018** [comment]
I'm so sorry about questioning!
1. I changed the _global_actor_optimizer_periodic_3000000 to actor.pt for correct loading and got the result.But when I evaluated the model trained in other scenarios in the same way, I got the same result.I tried many times to train the model in different scenarios and get results, but all the evaluations were the same.
2.  when I run sh eval_habitat_ft.sh,I got a error:
F0117 11:05:31.689309 17402 WindowlessContext.cpp:227] Check failed: device == 0 (1 vs. 0) glX context does not support multiple GPUs. Please compile with BUILD_GUI_VIEWERS=0 for multi-gpu support via EGL 

Could you please provide a detailed evaluation process and how various baseline algorithms are invoked?

Thank you!
